### ISSUE TITLE
宛先を空にしても@がついてしまう

### ISSUE THREAD

**Issue by tatsuya-asami** [yugo333/slack-reminder#3]
## 概要
- 入力必須であれば必須である旨をユーザーに伝えて、テキストが表示されないように(間違えてその値をslackに打ち込めないように)して欲しい。
- 必須でなければ不要な@を削除するなど機能を追加して欲しい

![image](https://user-images.githubusercontent.com/46734354/79706131-21907300-82f3-11ea-9030-9776d2e02922.png)

**Comment by yugo333** [comment]
誤入力などの場合にアラートをだすように致しました
https://github.com/yugo333/slack-reminder/pull/11
