### ISSUE TITLE
クリップボードにコピー機能が欲しい

### ISSUE THREAD

**Issue by tatsuya-asami** [yugo333/slack-reminder#4]
## 概要
- このアプリで作成した値は、コピーしてSlackに貼り付ける動作が期待される。
テキストボックスに値が入力された後に手動でコピーするのがちょっと面倒。ボタンをクリックしたらコピーされる機能が欲しい。

![image](https://user-images.githubusercontent.com/46734354/79706292-aaa7aa00-82f3-11ea-8865-0af76d313890.png)

**Comment by yugo333** [comment]
クリップボードにコピーbuttanを追加しました。
