### ISSUE TITLE
可能な限り小さい画面で使えるようにして欲しい

### ISSUE THREAD

**Issue by tatsuya-asami** [yugo333/slack-reminder#5]
## 概要
- 15インチのモニターだとこんな感じになる。可能な限り小さい画面上で使用出来るようにレイアウト修正をして欲しい。

![image](https://user-images.githubusercontent.com/46734354/79706411-20137a80-82f4-11ea-8084-f8d42b199278.png)

**Comment by yugo333** [comment]
レスポンシブの調整致しました
https://github.com/yugo333/slack-reminder/commit/1451c146b4b522ae43fba45cb01f8025c8aa429e
