### ISSUE TITLE
タブが増えてきた時にどこにあるのかわからなくなる

### ISSUE THREAD

**Issue by tatsuya-asami** [yugo333/slack-reminder#6]
## 概要
- スクショのような感じになりどこにあるかわからなくなる。
- ファビコンをつける等、タブの幅が狭くなってもどこにあるか判別出来るようにして欲しい。

![image](https://user-images.githubusercontent.com/46734354/79706574-a7f98480-82f4-11ea-96c8-f61a9043076c.png)

**Comment by yugo333** [comment]
ファビコン設定しました

https://github.com/yugo333/slack-reminder/commit/a68c90ccce341b5830d2ce6c54a7e9a553675035
