### ISSUE TITLE
slackのアイコンを回してもいいのか

### ISSUE THREAD

**Issue by tatsuya-asami** [yugo333/slack-reminder#7]
## 概要
- slackのアイコンを勝手に回していいものかどうか調べて欲しい。
- slackに限らず他のアイコンも一般的にどんな感じのルールになってるのか調べてもらえるとありがたい。

**Comment by yugo333** [comment]
slackロゴ
Slack マークには、Slack の名前とロゴ、Slack の製品のソースまたは起源を特定する単語、フレーズ、画像、またはその他の名称が含まれます。マークを改ざんしたり、Slack のスポンサーシップや推奨があるように見せたり、Slack を別のブランド（自分自身のブランドを含んで）と混乱するような仕方で使用しないでください。不明な点については、お気軽に pr@slack.com までお問い合わせください。

上記が公式サイトの使用条件で
今回のslack iconの回転は、改ざんには値しない気がするのだすが
Slack のスポンサーシップや推奨があるように見えてしまうので
そこが、よく無いかもしれません。

twitterはかなり細かく指定されていて
githubはslackみたいな感じでした

Twitter のロゴ
 • Twitter ロゴの色にはブルーまたは白のみ使用で
きます。
• ロゴの変更、回転、編集はできません。 
• ロゴのアニメーション化、セリフや鳴き声の追加、羽ばたかせる加工などはできません。
• 他の鳥や生物をロゴの周りに配置できません。 
• ロゴには吹き出しなどの要素を追加できません。
 • ロゴは擬人化できません。 • ロゴを過度に強調できません。
 • 旧バージョンのロゴは使用できません。 
• 本書に記載された空白スペースのガイドラインに従ってください。

GitHub　ロゴ
⭕️
OctocatまたはGitHubロゴを使用してGitHubにリンクする
ソーシャルボタンでマークを使用してGitHubプロファイルまたはプロジェクトにリンクする
OctocatまたはGitHubロゴを使用して、製品にGitHub統合が組み込まれていることを宣伝します
GitHubに関するブログ投稿またはニュース記事でOctocatまたはGitHubロゴを使用する

❌
これらのことをしないでください
アプリケーションのアイコンにOctocatまたはGitHubロゴを使用する
OctocatまたはGitHubロゴの変更バージョンを作成する
OctocatまたはGitHubロゴをロゴに統合する
許可なくGitHubアートワークを使用する
許可なくGitHubアートワークを販売する
色、寸法を変更するか、独自のテキスト/画像を追加します

**Comment by tatsuya-asami** [comment]
> 今回のslack iconの回転は、改ざんには値しない気がするのだすが
Slack のスポンサーシップや推奨があるように見えてしまうので
そこが、よく無いかもしれません。

なるほど。であれば問い合わせしてみた方がいいですね。（このレポジトリはパブリックなので、世界中の人が見える状態です。）

**Comment by yugo333** [comment]
問い合わせしています
返答待ちです
